apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: test-component--ygig
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: test-component--ygig
    app.kubernetes.io/part-of: test-app-hyll
  name: test-component--ygig
  namespace: e2e-test-pipelines-fskl
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: test-component--ygig
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: test-component--ygig
    spec:
      containers:
      - image: quay.io/psturc/test-images:81dccd9da5af4a94a3dcb45f47fc6090
        imagePullPolicy: Always
        livenessProbe:
          httpGet:
            path: /
            port: 8081
          initialDelaySeconds: 10
          periodSeconds: 10
        name: container-image
        ports:
        - containerPort: 8081
        readinessProbe:
          initialDelaySeconds: 10
          periodSeconds: 10
          tcpSocket:
            port: 8081
        resources: {}
status: {}
